name: Download and Upload Chromas Daily

on:
  schedule:
    - cron: '0 7 * * *'  # يوميًا الساعة 7 صباحًا UTC (8 صباحًا الجزائر)
  workflow_dispatch:

jobs:
  download-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp requests google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2

      - name: Run Script
        env:
          DRIVE_CLIENT_ID: ${{ secrets.DRIVE_CLIENT_ID }}
          DRIVE_CLIENT_SECRET: ${{ secrets.DRIVE_CLIENT_SECRET }}
          DRIVE_REFRESH_TOKEN: ${{ secrets.DRIVE_REFRESH_TOKEN }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: python download_and_upload_chromas.py
